export class CustomerData {
    customerId: string;
    customerName: string;
    countryId: string;
    currencyId: string;
    deptId: string;
    userId: string;
}




    // customerId
    // customerName
    // customerName2
    // customerTypeId
    // customerTypeSubId
    // customerAdd1
    // customerAdd2
    // customerAdd3
    // customerAdd4
    // customerAdd5
    // countryId
    // postalC
    // telephone1
    // telephone2
    // fax1
    // fax2
    // emailId1
    // emailId2
    // contact1
    // contact2
    // contact3
    // contact4
    // customerAccId
    // creditLimitA
    // invToDateA
    // invPaidA
    // approvedBy
    // currencyId
    // termId
    // salesmanId
    // remarks1
    // remarks2
    // userId
    // entryDate
    // createDate
    // traPortId
    // customerAdd12
    // customerAdd22
    // customerAdd32
    // customerAdd42
    // listInd
    // currentBal
    // lookupInd
    // gstRegNo
    // remarks3
    // remarks4
    // iName
    // iPass
    // iName2
    // iPass2
    // iCust
    // iType
    // iActive
    // glbCustId
    // deptId
    // businessRegNo
    // tdbCrNo
    // customerLogo
    // customerFooter1
    // customerFooter2
    // customerFooter3
    // customerFooter4
    // customerFooter5
    // customerFooter6
    // custEdocsFooter
    // custEdocsAdd
    // custEdocsFooterInd
    // parentAcctid
    // acctName
    // isCustomer
    // salesmanName
    // defLocCode
    // uen
    // nominatedCarrier
    // buName
    // buId
    // isInvoiceable
    // chkCnbLicNo
    // consolidateInv
    // attention
    // chkPermitProduct
    // yyCustId
    // syCustId
    // includeInConsplrpt
    // defDhlSendersId
    // businessUnit
    // cancelCustId
    // dhlAcctNo
    // insPremiumRate
    // logoName
    // postalCode1
    // postalCode2
    // custStamp
    // invpartyId
